# Generated by Django 5.0 on 2023-12-26 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='universities',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='specialties',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('score_22', models.IntegerField()),
                ('score_23', models.IntegerField()),
                ('subjects', models.CharField(max_length=20)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.universities')),
            ],
        ),
    ]
